<a href="https://colab.research.google.com/github/narenoffl/TalentSpring-TsCoE-Python-Training-for-ML-AI/blob/master/Py4AIMLDay3B2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
x = 20
print(type(x))
print(id(x))

<class 'int'>
10915104


In [ ]:
def example(x):
  #statemen1 
  #statement2
  return x*x 
print(type(example))
print(id(example))

<class 'function'>
140236895443824


In [ ]:
#lambda functions
#lambda arguments :expression


In [ ]:
 L = lambda x:x*x
 print(L(4))

16


In [ ]:
print((lambda x: x * x)(5)) 

25


In [ ]:
f1 = lambda :True
f1()

True

In [ ]:
f2 =lambda x : 'even' if x%2 == 0 else 'odd'
f2(3)

'odd'

In [ ]:
f3 = lambda x,y :x+y 
f3(2,3)

5

In [ ]:
#MAP
#map(function,iteraror1,iterator2 ..)

lst = [1, 2, 3, 4, 5]

def map_example(x):
  return x+5
result = list(map(map_example,lst))
result

[6, 7, 8, 9, 10]

In [ ]:
list(map(lambda x: x + 5,lst))

[6, 7, 8, 9, 10]

In [ ]:
str_lst = ['welcome','to','ml','by','habeeb']
set(map(str.lower,str_lst))

{'by', 'habeeb', 'ml', 'to', 'welcome'}

In [ ]:
list(map(lambda x,y :x+y ,[1,2,3],[2,4,5]))

[3, 6, 8]

In [ ]:
#filter 
#filter(function,iterator)
#lst = [1, 2, 3, 4, 5]
print(lst)
list(filter(lambda x: x%2 == 0,lst))

[1, 2, 3, 4, 5]


[2, 4]

In [ ]:
#reduce
import functools as ft
r = ft.reduce(lambda x,y :x * y,lst)
r

120

In [ ]:
from functools import reduce
r = reduce(lambda x,y:x * y,lst)
r

120

In [ ]:
import operator
from functools import reduce
r =  reduce(operator.mul,lst)
r
help(operator)

In [ ]:
import numpy as np
a = np.array(10)
print(type(a))


<class 'numpy.ndarray'>


In [ ]:
b = np.arange(1,11)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
c = np.arange(1,13).reshape(4,3)
print(c)
print(c.shape)
print(c.ndim)
print(c.size)
print('Number of Rows ',c.shape[0])
print('Number of Columns' ,c.shape[1])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
2
12
Number of Rows  4
Number of Columns 3


In [ ]:
d = np.arange(1,10).reshape(3,3)
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(np.sum(d,axis=0))

[12 15 18]


In [ ]:
e = np.arange(1,13).reshape(3,2,-1) #number of matrices number of rows number ofcolumns
print(e)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [ ]:
#[]
#[[]]
#[[[]]]

In [ ]:
np.random.seed(1)
f = np.random.randint(1,10,size=(4,3))
print(f)

[[6 9 6]
 [1 1 2]
 [8 7 3]
 [5 6 3]]
